YoutubeSearch/McViewer/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from . import views


urlpatterns = [
    path('', views.welcome, name="welcome"),
    path('login', views.loginprofile, name="login"),
    path('sign-up', views.signUp, name="sign_up"),
    path('home', views.index, name="home_page"),
    path('search', views.searchResult, name="search_result"),
    path('getRelatedSearch/<str:id>', views.getRelatedSearch, name="getRelatedSearch"),
    path('edit-profile',views.editProfile, name="edit_profile"),
    path('network', views.network, name = "network"),
    path('network/<str:referral_code>', views.privateNetwork, name = "private_network"),
    path('create-network', views.createNetwork, name = "create_network"),
]

YoutubeSearch/YoutubeSearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('McViewer.urls')),

    path('', TemplateView.as_view(template_name='base.html')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

YoutubeSearch/McViewer/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime

class UserProfile(models.Model):
    cover_photo = models.ImageField(upload_to='images', default="images/default-cover.jpg")
    display_picture = models.ImageField(upload_to='images', default="images/default-display.jpg")
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class Search(models.Model):
    date_searched = models.DateTimeField(default=timezone.now)
    text = models.CharField(max_length=255,default="None")
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, blank=True, null=True)
    title = models.CharField(max_length=255,default="None")
    video_id = models.CharField(max_length=255,default="None")
    thumbnail = models.ImageField(default='images/default-thumbnail.jpg', upload_to='images')

class PrivateNetwork(models.Model):
    users = models.ManyToManyField(UserProfile, blank=True)
    referral_code = models.CharField(max_length=255,default="None")
    title = models.CharField(max_length=255,default="None")
    date_created = models.DateTimeField(default=timezone.now)
    

YoutubeSearch/McViewer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class ImageUploadForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()

YoutubeSearch/McViewer/views.py
import requests
from isodate import parse_duration
from django.shortcuts import render, redirect

from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponse
from django.contrib.auth.models import User
from .models import *
from django.contrib.auth import login, authenticate, logout
from django.forms import ValidationError
from datetime import date
from .forms import *
from django.contrib.auth.decorators import login_required

# This method checks whether the user performing the request is authenticated.
# If they are authenticated, meaning they have signed up for McViewer, they are redirected to their homepage.
# If they are not authenticated, the welcome page is rendered where the user is give the opportunity to sign up.
def welcome(request):
    if request.user.is_authenticated:
        return redirect('home_page')
    return render(request, "welcome.html")

# This method renders the user's dashboard upon sign-in. 
# The user's 3 most recent searches are displayed by filtering all Search objects attached to this specific user
# and then ordering them by how recent the Search objects were created.
@login_required(login_url='login')
def index(request):
    user_profile = UserProfile.objects.get(user=request.user)
    recent_searches = Search.objects.filter(user_profile=user_profile).order_by('-date_searched')
    return render(request, 'home_page.html', {
        'userprofile': user_profile,
        'recentSearches': recent_searches,
        'numOfSearches': len(recent_searches)
    })

# This method provides the sign-up logic for McViewer.
# Upon clicking the sign-up button, all of the user's inputs are received from the sign-up form.
# Input validation occurs by checking whether the email or username inputted by the user are already in use
# by filtering through all Users in the database and checking is any User has that particular username or email.
# If this is the case, the appropriate error message is displayed.
# If the input validation checks are passed, a User object is created, a UserProfile object is created, the user is 
# authenticated and logged in.
# Finally, the user is redirected to their dashboard.
def signUp(request):
    if request.method == "POST" and "submitProfile" in request.POST:
        the_first_name = request.POST.get("first_name")
        the_last_name = request.POST.get("last_name")
        username = request.POST.get("username")
        the_email = request.POST.get("email")
        raw_password = request.POST.get("password")

        if User.objects.filter(username=username).exists():
            context = {'error':'The username you entered has already been taken. Please try another username.'}
            return render(request, 'sign_up.html', context)

        elif User.objects.filter(email=the_email).exists():
            context = {'error':'The email you entered has already been taken. Please try another email.'}
            return render(request, 'sign_up.html', context)

        user = User.objects.create_user(username = username, first_name = the_first_name, last_name = the_last_name, email = the_email, password = raw_password)
        userprofile = UserProfile.objects.create(
            user = user,
        )
        userAccount = authenticate(username=username, password=raw_password)
        login(request, userAccount)
        return redirect('home_page')
    return render(request, 'sign_up.html')

# This method provides the sign-in logic for McViewer.
# Upon clicking the "Sign up" button, all of the user's inputs are received from the sign-in form.
# If a User with the inputted email exists, check that the inputted password matches that user's email.
# If the email and password match, log the user in and send the user to their ddashboard.
# If the email and password do not match, display an error message to the user telling them that they
# inputted the wrong password. The user is allowed to try a new password.
# If there is no User with the inputted email that exists, display an error message to the user telling
# them that they have inputted an invalid email. The user is allowed to try a new email.
def loginprofile(request):
    logout(request)
    if request.method == "POST" and "login" in request.POST:
        the_email = request.POST.get("email")
        raw_password = request.POST.get("password")
        if User.objects.filter(email = the_email).exists():
            user = User.objects.get(email = the_email)
            if user.check_password(raw_password) and user.is_authenticated:
                login(request, user)
                return redirect('home_page')
            else:
                context = {'error':'You have entered an invalid password.'}
                return render(request, 'sign_in.html', context)
        else:   
            context = {'error':'You have entered an invalid email.'}
            return render(request, 'sign_in.html', context)

    return render(request, 'sign_in.html')

# This method allows you to search for a Youtube video based on the user's search input.
# Upon entering a search, we make an API call to Youtube's API.
# We then obtain all the videos obtained from the getSearchedVideos method.
# A Search object is only created if a Search object associated with that user profile and the title or search text provided doesn't already exist.
# If the user already has 3 searches, it will delete the least recently created Search.
# The first video result is displayed in large with the other video results displayed on the side.
@login_required(login_url='login')
def searchResult(request):
    try:
        if request.method == "GET":
            search = request.GET.get("search")
            user_profile = UserProfile.objects.get(user=request.user)

            videos = getSearchedVideos(search, 7)
            
            if Search.objects.filter(user_profile=user_profile, title=videos[0]['title']).exists():
                newSearch = Search.objects.get(user_profile=user_profile, title=videoDisplayed['title'])
                newSearch.text = videoDisplayed['title']
                newSearch.date_searched = date.today()
            elif Search.objects.filter(user_profile=user_profile, text=videos[0]['title']).exists():
                newSearch = Search.objects.get(user_profile=user_profile, text=videoDisplayed['title'])
                newSearch.title = videoDisplayed['title']
                newSearch.date_searched = date.today()
            else: 
                newSearch = Search.objects.create(
                    text = search,
                    date_searched = date.today(),
                    user_profile = user_profile,
                    title = videos[0]['title'],
                    video_id = videos[0]['id'],
                    thumbnail = videos[0]['thumbnail']
                )
            
                if Search.objects.filter(user_profile=user_profile).count() > 3:
                    earliest_search = Search.objects.filter(user_profile=user_profile).order_by('id').first()
                    earliest_search.delete()
            newSearch.save()

            return render(request, 'search.html', {
                'search': newSearch,
                'videoDisplayed': videos[0],
                'upNextVideos' : videos[1:]
                })
    except:
        return redirect('home_page')

# This method retrieves the video results based on the search provided on the home page.
# It makes an API call to Youtube's API.
# We first retrieve all video results obtained by the search and
# make a list of all the video IDs from each video.
# We then obtain all the necessary information for each video (title, ID, duration, thumbnail).
# These videos obtained are then returned to the SearchResult method so they can be rendered in the template.  
def getSearchedVideos(search, numResults):
    search_url = 'https://www.googleapis.com/youtube/v3/search'
    video_url = 'https://www.googleapis.com/youtube/v3/videos'

    search_params = {
            'part' : 'snippet',
            'q' : search,
            'key' : settings.YOUTUBE_API_KEY,
            'maxResults' : numResults,
            'type' : 'video'
        }
    video_ids = []
    res = requests.get(search_url, params = search_params)
        
    search_results = res.json()['items']
    for result in search_results:
        video_ids.append(result['id']['videoId'])
    
    video_params = {
        'key' : settings.YOUTUBE_API_KEY,
        'part' : 'snippet,contentDetails',
        'id' : ','.join(video_ids),
        'maxResults' : numResults
    }
    res = requests.get(video_url, params = video_params)

    video_results = res.json()['items']

    videos = []
    for result in video_results:
        video_data = {
            'title' : result['snippet']['title'],
            'id' : result['id'],
            'duration' : parse_duration(result['contentDetails']['duration']),
            'thumbnail' : result['snippet']['thumbnails']['high']['url']
        }
        videos.append(video_data)
    
    return videos

# This method returns all the videos related to the video clicked on either the home page or the search page.
# We make an API call to Youtube's API.
# We first retrieve all the video results based on the ID given by the video clicked.
# We then obtain all the necessary information for each video (title, ID, duration, thumbnail).
# The video clicked is then displayed in large with all the other related videos on the side in the template.
@login_required(login_url='login')
def getRelatedSearch(request, id):
    try:    
        search_url = 'https://www.googleapis.com/youtube/v3/search'
        video_url = 'https://www.googleapis.com/youtube/v3/videos'
        
        related_params = {
            'part' : 'snippet',
            'key' : settings.YOUTUBE_API_KEY,
            'maxResults' : 6,
            'relatedToVideoId' : id,
            'type' : 'video'
        }
        video_ids = []

YoutubeSearch/McViewer/templates/create_network.html
{% extends "base.html" %}

{% load static %}


{% block content %}
<div class="header">
  <div class="container-fluid">

      <!-- Body -->
      <div class="header-body">
          <div class="row align-items-end">
              <div class="col">

                  <!-- Title -->
                  <h1 class="header-title">
                      Create a Private Network
                  </h1>

              </div>

          </div> <!-- / .row -->
      </div> <!-- / .header-body -->

  </div>
</div> <!-- / .header -->

<div class="card" style="display: flex; justify-content: center; margin: 2.5em 5em;">
  <div class="card-body">

    <!-- Form -->
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-row">
        <div class="col-12 col-md-6 mb-3">
          <label for="validationServer01">Network Name</label>
          <input name="network_name" type="text" class="form-control is-valid"
            id="validationServer01" placeholder="Name" required>
          <div class="valid-feedback">
          </div>
        </div>
        <div class="col-12 col-md-6 mb-3">
          <label for="validationServer02">Referral Code</label>
          <input name="referral-code" type="text" class="form-control is-valid"
            id="validationServer02" placeholder="Code" required>
          <div class="valid-feedback">
          </div>
        </div>
      </div>
      {% if error %}
     <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{error}}
        <!-- Button -->
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>

      </div>
      {% endif %}


      <!-- Button -->
      <button class="btn btn-primary" name="createNetwork" type="submit">Create Network</button>
    </form>

  </div>
</div>





{% endblock content %}

{% block javascript %}

{% endblock javascript %}

YoutubeSearch/McViewer/templates/edit_profile.html
{% extends "base.html" %}

{% load static %}


{% block content %}
<div class="header">
  <div class="container-fluid">

    <!-- Body -->
    <div class="header-body">
      <div class="row align-items-end">
        <div class="d-flex justify-content-flex-start align-items-flex-end">

          <div>

            <!-- Avatar -->
            <div class="avatar avatar-xxl header-avatar-top">
              <img src="{{ request.user.userprofile.display_picture.url }}" alt="..."
                class="avatar-img rounded-circle border border-4 border-body">
            </div>

          </div>

          <!-- Title -->
          <h1 class="header-title" style="margin-top: 3.5em; margin-left: 1em;">
            My Profile
          </h1>

        </div>

      </div> <!-- / .row -->
    </div> <!-- / .header-body -->

  </div>
</div> <!-- / .header -->

<div class="card" style="display: flex; justify-content: center; margin: 2.5em 5em;">
  <div class="card-body">

    <!-- Form -->
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-row">
        <div class="col-12 col-md-6 mb-3">
          <label for="validationServer01">First Name</label>
          <br>
          <h3>
            {{request.user.first_name}}
          </h3>
          <div class="valid-feedback">
          </div>
        </div>
        <div class="col-12 col-md-6 mb-3">
          <label for="validationServer02">Last name</label>
          <br>
          <h3>
            {{request.user.last_name}}
          </h3>
          <div class="valid-feedback">
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col-12 col-md-6 mb-3">
          <label for="validationServer03">Username</label>
          <input name="username" value="{{request.user.username}}" class="form-control is-valid" id="validationServer02"
            placeholder="Username" required>
          <div class="valid-feedback">
          </div>
        </div>
        <div class="col-12 col-md-6 mb-3">
          <label for="validationServer03">Email</label>
          <input name="email" value="{{request.user.email}}" type="email" class="form-control is-valid"
            id="validationServer02" placeholder="Email" required>
          <div class="valid-feedback">
          </div>
        </div>
      </div>
      <div class="form-row">
        <div class="col12 col-md-6 mb-3">
          <label for="validationServer04">Display Picture</label>
          <br>
          <input type="file" name="image" accept="image/*">
        </div>
      </div>
      {% if error %}
      <div class="form-row">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          {{error}}

          <!-- Button -->
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>

        </div>
      </div>
      {% endif %}
  </div>

  <!-- Button -->
  <button class="btn btn-primary" name="editProfile" type="submit">Save Changes</button>
  </form>

</div>
</div>





{% endblock content %}

{% block javascript %}

{% endblock javascript %}

YoutubeSearch/McViewer/templates/example.html
{% extends 'base.html' %}

{% block content %}
<!-- HEADER -->
<div class="header">
    <div class="container-fluid">

      <!-- Body -->
      <div class="header-body">
        <div class="row align-items-end">
          <div class="col">

            <!-- Pretitle -->
            <h6 class="header-pretitle">
              Overview
            </h6>

            <!-- Title -->
            <h1 class="header-title">
              Dashboard
            </h1>

          </div>
          
        </div> <!-- / .row -->
      </div> <!-- / .header-body -->

    </div>
  </div> <!-- / .header -->

{% endblock content %}

YoutubeSearch/McViewer/templates/home_page.html
{% extends "base.html" %}

{% load static %}


{% block content %}

<!-- MAIN CONTENT
    ================================================== -->
<div class="main-content">



  <!-- HEADER -->
  <div class="header">

    <!-- Image -->
    <img src="{{ userprofile.cover_photo.url }}" class="header-img-top" alt="...">

    <div class="container-fluid">

      <!-- Body -->
      <div class="header-body mt-n5 mt-md-n6">
        <div class="row align-items-end">
          <div class="col-auto">

            <!-- Avatar -->
            <div class="avatar avatar-xxl header-avatar-top">
              <img src="{{ userprofile.display_picture.url }}" alt="..."
                class="avatar-img rounded-circle border border-4 border-body">
            </div>

          </div>
          <div class="col mb-3 ml-n3 ml-md-n2">
            <!-- Pretitle -->
            <h6 class="header-pretitle">
              Welcome to the McViewer Network,
            </h6>

            <!-- Title -->
            <h1 class="header-title">
              {{userprofile.user.first_name}} {{userprofile.user.last_name}}
            </h1>

          </div>

        </div> <!-- / .row -->
        <div class="row align-items-center">
          <div class="col">

            <!-- Nav -->
            <ul class="nav nav-tabs nav-overflow header-tabs">
            </ul>

          </div>
        </div>
      </div> <!-- / .header-body -->

    </div>
  </div>



  <!-- CONTENT -->
  {% if numOfSearches < 1 %}
  <div class="col-12" style="padding: 0em 2.45em;">
    <div class="alert alert-success" role="alert">

      <!-- Heading -->
      <h4 class="alert-heading">Welcome to the McViewer Network!</h4>
      
      <!-- Divider -->
      <hr>

      <!-- Text -->
      <p>
        Seemlessly search through the infinitely vast world of online video content! Check out Our Network to see what
        people like you are searching for!
      </p>

    </div>
  </div>

  {% endif %}
  <div data-list='{"valueNames": ["name"]}'>
    <div class="container-fluid" data-list='{"valueNames": ["name"], "listClass": "listAlias"}'>
      <div class="row mb-4">
        <div class="col">


          <div class="card">
            <div class="card-body">

              <!-- Form -->
              <form action="{% url 'search_result' %}" method="GET">
                {% csrf_token %}
                <input type="text" name="search" class="form-control form-control-rounded" placeholder="Search Here!"
                  required>
              </form>

            </div>

          </div>

        </div>
        <div class="col-auto">

          <!-- Navigation (button group) -->
          <div class="nav btn-group" role="tablist">
            <button class="btn btn-lg btn-white active" data-toggle="tab" data-target="#tabPaneOne" role="tab"
              aria-controls="tabPaneOne" aria-selected="true">
              <span class="fe fe-grid"></span>
            </button>
            <button class="btn btn-lg btn-white" data-toggle="tab" data-target="#tabPaneTwo" role="tab"
              aria-controls="tabPaneTwo" aria-selected="false">
              <span class="fe fe-list"></span>
            </button>
          </div> <!-- / .nav -->

        </div>
      </div> <!-- / .row -->

      <!-- Tab content -->
      <div class="tab-content">
        <div class="tab-pane fade active show" id="tabPaneOne" role="tabpanel">
          <div class="row listAlias">
            {% for search in recentSearches %}
            <div class="col-12 col-md-6 col-xl-4">

              <!-- Card -->
              <div class="card">

                <!-- Image -->
                <a href="{% url 'getRelatedSearch' search.video_id %}">
                  <img src="{{ search.thumbnail }}" alt="..." class="card-img-top">
                </a>

                <!-- Body -->
                <div class="card-body">
                  <div class="row align-items-center">
                    <div class="col">

                      <!-- Title -->
                      <h4 class="mb-2 name">
                        <a href="{% url 'getRelatedSearch' search.video_id %}">{{ search.text }}</a>
                      </h4>

                      <!-- Subtitle -->
                      <p class="card-text small text-muted">
                        {{ search.title }}
                      </p>

                    </div>
                  </div> <!-- / .row -->
                </div>
              </div>

            </div>
            {% endfor %}

          </div> <!-- / .row -->
        </div>
        <div class="tab-pane fade" id="tabPaneTwo" role="tabpanel">
          <div class="row list">
            {% for search in recentSearches %}
            <div class="col-12">

              <div class="card">
                <div class="card-body">
                  <div class="row align-items-center">
                    <div class="col-auto">

                      <!-- Avatar -->
                      <a href="{% url 'getRelatedSearch' search.video_id %}" class="avatar avatar-lg avatar-4by3">
                        <img src="{{ search.thumbnail }}" alt=" ..." class="avatar-img rounded">
                      </a>

                    </div>
                    <div class="col ml-n2">

                      <!-- Title -->
                      <h4 class="mb-1 name">
                        <a href="{% url 'getRelatedSearch' search.video_id %}">{{ search.text }}</a>
                      </h4>

                      <!-- Text -->
                      <p class="card-text small text-muted mb-1">
                        <time datetime="2018-06-21">{{ search.title }}</time>
                      </p>

                      <!-- Progress -->
                      <div class="row align-items-center no-gutters">
                        <div class="col-auto">

                        </div>
                      </div> <!-- / .row -->

                    </div>
                    <div class="col-auto">

                    </div>
                  </div> <!-- / .row -->
                </div> <!-- / .card-body -->
              </div>

            </div>
            {% endfor %}
          </div> <!-- / .row -->
        </div>
      </div> <!-- / .tab-content -->

    </div>
  </div>

</div> <!-- / .main-content -->


{% endblock content %}

{% block javascript %}

{% endblock javascript %}

YoutubeSearch/McViewer/templates/sidebar.html
{% load static %}
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light" id="sidebar">
    <div class="container-fluid">

        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidebarCollapse"
            aria-controls="sidebarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        
        <a style="display: flex; justify-content: center;"href="{% if request.user.is_authenticated %} {% url 'home_page' %} {% else %} {% url 'welcome' %} {% endif %}">
            <img src="http://127.0.0.1:8000/media/images/logo.jpg" width="50%" height="50%" alt="..." >
        </a> 
        

        <!-- User (xs) -->
        <div class="navbar-user d-md-none">

            <!-- Dropdown -->
            <div class="dropdown">

                <!-- Toggle -->
                <a id="sidebarIcon" class="dropdown-toggle" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    <div class="avatar avatar-sm avatar-online">
                        {% if request.user.is_authenticated %}
                        <img src="{{ request.user.userprofile.display_picture.url }}" class="avatar-img rounded-circle"
                            alt="...">
                        {% else %}
                        <img src="http://127.0.0.1:8000/media/images/default-display.jpg" class="avatar-img rounded-circle"
                            alt="...">
                        {% endif %}
                    </div>
                </a>

            </div>

        </div>

        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidebarCollapse">

            <!-- Form -->
            <form class="mt-4 mb-3 d-md-none">
                <div class="input-group input-group-rounded input-group-merge">
                    <input type="search" class="form-control form-control-rounded form-control-prepended"
                        placeholder="Search" aria-label="Search">
                    <div class="input-group-prepend">
                        <div class="input-group-text">
                            <span class="fe fe-search"></span>
                        </div>
                    </div>
                </div>
            </form>

            <!-- Navigation -->
            
            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'home_page' %}">
                        <i class="fe fe-home"></i><span  style="font-weight: 800; text-decoration: underline;">Home</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'edit_profile' %}">
                        <i class="fe fe-user"></i><span  style="font-weight: 800; text-decoration: underline;">My Profile</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'network' %}">
                        <i class="fe fe-grid"></i><span  style="font-weight: 800; text-decoration: underline;">Global Network</span>
                    </a>
                </li>

                {% if request.user.userprofile.privatenetwork_set.all.count > 0 %}

                <li class="nav-item">
                    <a class="nav-link collapsed" href="#sidebarComponents" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="sidebarComponents">
                      <i class="fe fe-git-branch"></i> <span style="font-weight: 800; text-decoration: underline;"> My Private Networks </span>
                    </a>
                    {% for network in request.user.userprofile.privatenetwork_set.all %}
                    <div class="collapse" id="sidebarComponents" style="">
                      <ul class="nav nav-sm flex-column">
                        <li>
                          <a href="{% url 'private_network' network.referral_code %}" class="nav-link">
                            {{network.title}}
                          </a>
                        </li>
                      </ul>
                    </div>
                    {% endfor %}
                </li>
                {% endif %}
                
                {% else %}
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'login' %}">
                        <i class="fe fe-home"></i><span  style="font-weight: 800; text-decoration: underline;">Sign In</span>
                    </a>
                </li>
                {% endif %}
            </ul>

            <!-- Divider -->
            {% if request.user.is_authenticated %}
            <hr class="navbar-divider my-3">

            <!-- Heading 
            <h6 class="navbar-heading">
                Documentation
            </h6>-->

            
            <!-- Push content down -->
            <div class="mt-auto"></div>




            <!-- User (md) -->
            <div class="navbar-user d-none d-md-flex" id="sidebarUser">

                <!-- Icon -->

                <!-- Dropup -->

                <div class="dropup">

                    <!-- Toggle -->
                    <a id="sidebarIconCopy" class="dropdown-toggle" role="button" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <div class="avatar avatar-sm avatar-online">
                            <img src="{{ request.user.userprofile.display_picture.url }}"" class="avatar-img rounded-circle"
                                alt="...">
                        </div>
                    </a>

                    <!-- Menu -->
                    <div class="dropdown-menu" aria-labelledby="sidebarIconCopy">
                        <a href="{% url 'edit_profile' %}" class="dropdown-item">Profile</a>
                        <hr class="dropdown-divider">
                        <a href="{% url 'login' %}" class="dropdown-item">Logout</a>
                    </div>

                </div>
                


            </div>
            {% endif %}


        </div> <!-- / .navbar-collapse -->

    </div>
</nav>